"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Filter, X } from "lucide-react";
import type { ArrayFilterKey, ReportsFiltersProps } from "./types";
import {
  commonTags,
  generatedByOptions,
  reportPeriods,
  reportStatuses,
  reportTypes,
} from "./constants";
import { CheckboxFilterGroup } from "./checkbox-filter-group";
import { DateRangeFilter } from "./date-range-filter";
import { TagsFilter } from "./tags-filter";

export function ReportsFilters({ filters, onFiltersChange, onClearFilters }: ReportsFiltersProps) {
  const [dateRange, setDateRange] = useState<{ start?: Date; end?: Date }>({
    start: filters.dateRange?.start,
    end: filters.dateRange?.end,
  });

  const handleArrayFilterChange = (key: ArrayFilterKey, value: string, checked: boolean) => {
    const current = filters[key] || [];
    const next = checked ? [...current, value] : current.filter((item) => item !== value);
    onFiltersChange({ [key]: next });
  };

  const handleDateRangeChange = (type: "start" | "end", date?: Date) => {
    const newDateRange = { ...dateRange, [type]: date };
    setDateRange(newDateRange);

    if (newDateRange.start && newDateRange.end) {
      onFiltersChange({ dateRange: { start: newDateRange.start, end: newDateRange.end } });
    }
  };

  const clearAllFilters = () => {
    setDateRange({ start: undefined, end: undefined });
    onClearFilters();
  };

  const hasActiveFilters = !!(
    filters.type?.length ||
    filters.status?.length ||
    filters.period?.length ||
    filters.dateRange?.start ||
    filters.dateRange?.end ||
    filters.generatedBy?.length ||
    filters.tags?.length ||
    filters.search
  );

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2">
            <Filter className="h-5 w-5" />
            Filters
          </CardTitle>
          {hasActiveFilters && (
            <Button variant="ghost" size="sm" onClick={clearAllFilters}>
              <X className="h-4 w-4 mr-1" />
              Clear All
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Search */}
        <div className="space-y-2">
          <Label htmlFor="search">Search</Label>
          <Input
            id="search"
            placeholder="Search reports..."
            value={filters.search || ""}
            onChange={(e) => onFiltersChange({ search: e.target.value })}
          />
        </div>

        {/* Report Types */}
        <CheckboxFilterGroup
          label="Report Types"
          idPrefix="type"
          options={reportTypes}
          selected={filters.type}
          onToggle={(value, checked) => handleArrayFilterChange("type", value, checked)}
        />

        {/* Status */}
        <CheckboxFilterGroup
          label="Status"
          idPrefix="status"
          options={reportStatuses}
          selected={filters.status}
          onToggle={(value, checked) => handleArrayFilterChange("status", value, checked)}
        />

        {/* Period */}
        <CheckboxFilterGroup
          label="Period"
          idPrefix="period"
          options={reportPeriods}
          selected={filters.period}
          onToggle={(value, checked) => handleArrayFilterChange("period", value, checked)}
        />

        <DateRangeFilter
          start={dateRange.start}
          end={dateRange.end}
          onSelect={handleDateRangeChange}
        />

        {/* Generated By */}
        <CheckboxFilterGroup
          label="Generated By"
          idPrefix="generated-by"
          options={generatedByOptions}
          selected={filters.generatedBy}
          onToggle={(value, checked) => handleArrayFilterChange("generatedBy", value, checked)}
        />

        {/* Tags */}
        <TagsFilter
          options={commonTags}
          selected={filters.tags}
          onToggle={(value, checked) => handleArrayFilterChange("tags", value, checked)}
        />
      </CardContent>
    </Card>
  );
}
