/**
 * tests/certificate-verification.test.ts
 *
 * Front-office certificate reads (plan item UI-03, decision D2):
 * - Public verification by the verificationCode stored in the database
 *   (ACTIVE vs REVOKED vs unknown code). Codes are generated by the issue
 *   mutation and read back — never fabricated client-side.
 * - Member-scoped reads: a member lists/detail-fetches only their own
 *   certificates, matched by studentEmail, ACTIVE-only for the list.
 *
 * Runs against real Postgres through the learning service layer (no HTTP).
 * Isolation: every row created here is tagged with RUN_ID and removed in
 * afterAll; the tests pass on an empty database and on a seeded one.
 */

import { afterAll, beforeAll, describe, expect, test } from "bun:test";

import { createCourse } from "@/lib/services/learning/course-mutations";
import type { CreateCourseInput } from "@/lib/services/learning/schemas";
import { issueCertificate, updateCertificate } from "@/lib/services/learning/certificate-mutations";
import {
  getCertificateForStudent,
  listCertificatesForStudent,
} from "@/lib/services/learning/certificate-queries";
import { verifyCertificateByCode } from "@/lib/services/learning/certificate-verification";

import {
  cleanupAll,
  coursePayload,
  RUN_ID,
  signUpWithRole,
  trackCertificate,
  trackCourse,
} from "./learning-api/helpers";

const STUDENT_EMAIL = `cert-verify-student-${RUN_ID}@example.com`;
const OTHER_EMAIL = `cert-verify-other-${RUN_ID}@example.com`;

function certCourseName(n: number): string {
  return `Cert Verify Course ${n} ${RUN_ID}`;
}

/** State captured in beforeAll for the assertions below. */
const issued = {
  actorId: "",
  courseId: "",
  courseTitle: "",
  activeId: "",
  activeCode: "",
  secondActiveId: "",
  revokedId: "",
  revokedCode: "",
  otherId: "",
  otherCode: "",
};

beforeAll(async () => {
  // A real course backs every certificate: issueCertificate asserts the
  // courseId exists and the column is a uuid FK.
  const member = await signUpWithRole("member", null);
  issued.actorId = member.userId;

  const createdCourse = await createCourse(
    coursePayload("cert-verify") as CreateCourseInput,
    member.userId,
  );
  trackCourse(createdCourse.id);
  issued.courseId = createdCourse.id;
  issued.courseTitle = createdCourse.title;

  const inputs = [
    {
      courseId: createdCourse.id,
      courseName: certCourseName(1),
      studentName: `Verify Student ${RUN_ID}`,
      studentEmail: STUDENT_EMAIL,
      instructorName: createdCourse.instructor?.name ?? "Vera Instructor",
      grade: "A",
    },
    {
      courseId: createdCourse.id,
      courseName: certCourseName(2),
      studentName: `Verify Student ${RUN_ID}`,
      studentEmail: STUDENT_EMAIL,
      instructorName: createdCourse.instructor?.name ?? "Vera Instructor",
      grade: "B+",
    },
    {
      courseId: createdCourse.id,
      courseName: certCourseName(3),
      studentName: `Verify Student ${RUN_ID}`,
      studentEmail: STUDENT_EMAIL,
      instructorName: createdCourse.instructor?.name ?? "Vera Instructor",
      grade: "C",
    },
    {
      courseId: createdCourse.id,
      courseName: certCourseName(4),
      studentName: `Other Member ${RUN_ID}`,
      studentEmail: OTHER_EMAIL,
      instructorName: createdCourse.instructor?.name ?? "Vera Instructor",
      grade: "A-",
    },
  ];

  const certs = await Promise.all(inputs.map((input) => issueCertificate(input, issued.actorId)));
  for (const cert of certs) trackCertificate(cert.id);

  issued.activeId = certs[0].id;
  issued.activeCode = certs[0].verificationCode;
  issued.secondActiveId = certs[1].id;
  issued.revokedId = certs[2].id;
  issued.revokedCode = certs[2].verificationCode;
  issued.otherId = certs[3].id;
  issued.otherCode = certs[3].verificationCode;

  // Revoke the third certificate so REVOKED lookups can be exercised.
  await updateCertificate(issued.revokedId, { status: "revoked" });
});

describe("certificate verification by stored code", () => {
  test("returns the ACTIVE certificate for a stored verification code", async () => {
    const result = await verifyCertificateByCode(issued.activeCode);
    expect(result).not.toBeNull();
    if (!result) return;
    expect(result.id).toBe(issued.activeId);
    expect(result.status).toBe("ACTIVE");
    expect(result.studentName).toBe(`Verify Student ${RUN_ID}`);
    expect(result.courseName).toBe(issued.courseTitle);
    expect(result.issuedAt).toBeInstanceOf(Date);
  });

  test("public projection never exposes the student's email", async () => {
    const result = await verifyCertificateByCode(issued.activeCode);
    expect(result).not.toBeNull();
    if (!result) return;
    expect("studentEmail" in result).toBe(false);
    expect("email" in result).toBe(false);
  });

  test("reports REVOKED status for a revoked certificate", async () => {
    const result = await verifyCertificateByCode(issued.revokedCode);
    expect(result).not.toBeNull();
    if (!result) return;
    expect(result.id).toBe(issued.revokedId);
    expect(result.status).toBe("REVOKED");
    // Owner name stays visible even when revoked; the record is public-safe.
    expect(result.studentName).toBe(`Verify Student ${RUN_ID}`);
  });

  test("returns null for an unknown verification code", async () => {
    const result = await verifyCertificateByCode(`NOPE-${RUN_ID}-0000`);
    expect(result).toBeNull();
  });
});

describe("member certificate reads (own certificates only)", () => {
  test("member list returns only their own ACTIVE certificates", async () => {
    const list = await listCertificatesForStudent(STUDENT_EMAIL);
    expect(list).toHaveLength(2);
    const ids = list.map((cert) => cert.id).sort();
    expect(ids).toEqual([issued.activeId, issued.secondActiveId].sort());
    for (const cert of list) {
      expect(cert.status).toBe("active");
      expect(cert.studentEmail).toBe(STUDENT_EMAIL);
    }
  });

  test("member list excludes other members' certificates", async () => {
    const list = await listCertificatesForStudent(STUDENT_EMAIL);
    expect(list.some((cert) => cert.id === issued.otherId)).toBe(false);

    const otherList = await listCertificatesForStudent(OTHER_EMAIL);
    expect(otherList).toHaveLength(1);
    expect(otherList[0].id).toBe(issued.otherId);
  });

  test("member detail returns their own certificate", async () => {
    const own = await getCertificateForStudent(issued.activeId, STUDENT_EMAIL);
    expect(own).not.toBeNull();
    expect(own?.id).toBe(issued.activeId);
    expect(own?.verificationCode).toBe(issued.activeCode);
  });

  test("member detail refuses another member's certificate", async () => {
    const foreign = await getCertificateForStudent(issued.activeId, OTHER_EMAIL);
    expect(foreign).toBeNull();
  });

  test("member detail returns null for an unknown certificate id", async () => {
    const missing = await getCertificateForStudent(
      "00000000-0000-4000-8000-000000000000",
      STUDENT_EMAIL,
    );
    expect(missing).toBeNull();
  });
});

afterAll(async () => {
  await cleanupAll();
});
