"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Download, FileText, Trash2 } from "lucide-react";
import ReportRow from "./report-row";
import type { ReportsTableProps } from "./types";

export function ReportsTable({
  reports,
  onViewDetails,
  onDownload,
  onEdit,
  onDelete,
  onUpdateStatus,
}: ReportsTableProps) {
  const [selectedReports, setSelectedReports] = useState<string[]>([]);

  const handleSelectReport = (reportId: string, checked: boolean) => {
    if (checked) {
      setSelectedReports((prev) => [...prev, reportId]);
    } else {
      setSelectedReports((prev) => prev.filter((id) => id !== reportId));
    }
  };

  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedReports(reports.map((report) => report.id));
    } else {
      setSelectedReports([]);
    }
  };

  const handleBulkDownload = () => {
    selectedReports.forEach((reportId) => {
      const report = reports.find((r) => r.id === reportId);
      if (report) {
        onDownload(report);
      }
    });
    setSelectedReports([]);
  };

  const handleBulkDelete = () => {
    selectedReports.forEach((reportId) => {
      const report = reports.find((r) => r.id === reportId);
      if (report) {
        onDelete(report);
      }
    });
    setSelectedReports([]);
  };

  if (reports.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>No Reports Found</CardTitle>
          <CardDescription>There are no reports matching your current filters.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8">
            <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">
              Try adjusting your filters or generate a new report.
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Financial Reports</CardTitle>
            <CardDescription>
              Manage and view your financial reports and documentation
            </CardDescription>
          </div>
          {selectedReports.length > 0 && (
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">
                {selectedReports.length} selected
              </span>
              <Button variant="outline" size="sm" onClick={handleBulkDownload}>
                <Download className="h-4 w-4 mr-2" />
                Download Selected
              </Button>
              <Button variant="outline" size="sm" onClick={handleBulkDelete}>
                <Trash2 className="h-4 w-4 mr-2" />
                Delete Selected
              </Button>
            </div>
          )}
        </div>
      </CardHeader>
      <CardContent>
        <div className="rounded-md border overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-12">
                  <Checkbox
                    checked={selectedReports.length === reports.length}
                    onCheckedChange={(checked) => handleSelectAll(checked === true)}
                    aria-label="Select all rows"
                  />
                </TableHead>
                <TableHead className="min-w-[200px]">Report</TableHead>
                <TableHead className="min-w-[120px]">Type</TableHead>
                <TableHead className="min-w-[100px]">Period</TableHead>
                <TableHead className="min-w-[120px]">Status</TableHead>
                <TableHead className="min-w-[120px] hidden sm:table-cell">Generated By</TableHead>
                <TableHead className="min-w-[100px] hidden md:table-cell">Generated</TableHead>
                <TableHead className="min-w-[100px] hidden lg:table-cell">Downloads</TableHead>
                <TableHead className="w-[80px] text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((report) => (
                <ReportRow
                  key={report.id}
                  report={report}
                  selected={selectedReports.includes(report.id)}
                  onSelect={handleSelectReport}
                  onViewDetails={onViewDetails}
                  onDownload={onDownload}
                  onEdit={onEdit}
                  onDelete={onDelete}
                  onUpdateStatus={onUpdateStatus}
                />
              ))}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  );
}
