import React from "react";
import {
  Home,
  Users,
  Calendar,
  Megaphone,
  DollarSign,
  BarChart3,
  CalendarCheck,
  CreditCard,
  Shield,
  Settings,
  Cog,
  FileText,
  Tag,
  MessageSquare,
  Mail,
  Building,
  Briefcase,
  Award,
  BookOpen,
  Bell,
  Lock,
  Database,
  PieChart,
  Star,
  MapPin,
  QrCode,
  RefreshCw,
  Download,
  Receipt,
  Gift,
  Layers,
  Terminal,
  HardDrive,
  Key,
  ShieldCheck,
  Trophy,
  Flag,
  Book,
  GraduationCap,
  Medal,
  Users2,
  UserCog,
  UserPlus as UserPlusIcon,
  Image as ImageIcon,
  FileClock,
  Palette,
} from "lucide-react";
import { navigationData, navigationCategories, type NavItemData } from "@/lib/navigation-data";
import { getModuleForPath, type ModuleName } from "../../../../config/features";

export interface NavigationItem extends NavItemData {
  readonly icon: React.ReactNode;
  /** Module maturity gate attribution (config/features.ts); undefined for non-module sections. */
  readonly module?: ModuleName;
  readonly subItems?: readonly NavigationItem[];
}

// Icons keyed by nav item id — kept out of navigation-data.ts so that data
// (consumed server-side by src/lib/dashboard-access.ts, including from
// src/proxy.ts middleware) doesn't drag React/lucide-react along with it.
const icons: Record<string, React.ReactNode> = {
  dashboard: <Home className="h-4 w-4" />,
  "user-management": <UserCog className="h-4 w-4" />,
  "user-directory": <Users className="h-4 w-4" />,
  "user-roles": <ShieldCheck className="h-4 w-4" />,
  "user-security": <Lock className="h-4 w-4" />,
  memberships: <Users className="h-4 w-4" />,
  "member-directory": <Users className="h-4 w-4" />,
  "membership-tiers": <Layers className="h-4 w-4" />,
  "membership-applications": <UserPlusIcon className="h-4 w-4" />,
  "membership-renewals": <RefreshCw className="h-4 w-4" />,
  "member-analytics": <BarChart3 className="h-4 w-4" />,
  // UI-22: renamed from "member-analytics" in memberships.ts to dedupe the id.
  "membership-analytics": <BarChart3 className="h-4 w-4" />,
  events: <Calendar className="h-4 w-4" />,
  "event-calendar": <CalendarCheck className="h-4 w-4" />,
  "event-registrations": <Users className="h-4 w-4" />,
  "event-checkin": <QrCode className="h-4 w-4" />,
  "event-certificates": <Award className="h-4 w-4" />,
  "event-pricing": <Tag className="h-4 w-4" />,
  finance: <DollarSign className="h-4 w-4" />,
  "budget-management": <PieChart className="h-4 w-4" />,
  "dues-management": <CreditCard className="h-4 w-4" />,
  "invoices-billing": <Receipt className="h-4 w-4" />,
  "donations-grants": <Gift className="h-4 w-4" />,
  "financial-reports": <BarChart3 className="h-4 w-4" />,
  "payment-gateways": <CreditCard className="h-4 w-4" />,
  organization: <Building className="h-4 w-4" />,
  chapters: <MapPin className="h-4 w-4" />,
  committees: <Users2 className="h-4 w-4" />,
  "committee-workspaces": <Briefcase className="h-4 w-4" />,
  "committee-budgets": <DollarSign className="h-4 w-4" />,
  content: <FileText className="h-4 w-4" />,
  publications: <BookOpen className="h-4 w-4" />,
  "articles-news": <FileText className="h-4 w-4" />,
  announcements: <Megaphone className="h-4 w-4" />,
  "categories-tags": <Tag className="h-4 w-4" />,
  "media-library": <ImageIcon className="h-4 w-4" />,
  learning: <GraduationCap className="h-4 w-4" />,
  courses: <Book className="h-4 w-4" />,
  certifications: <Award className="h-4 w-4" />,
  "course-management": <Settings className="h-4 w-4" />,
  "certificate-management": <ShieldCheck className="h-4 w-4" />,
  "instructor-settings": <Cog className="h-4 w-4" />,
  forums: <MessageSquare className="h-4 w-4" />,
  "forum-categories": <Layers className="h-4 w-4" />,
  "forum-moderation": <Shield className="h-4 w-4" />,
  "user-reports": <Flag className="h-4 w-4" />,
  "job-board": <Briefcase className="h-4 w-4" />,
  awards: <Trophy className="h-4 w-4" />,
  "award-programs": <Medal className="h-4 w-4" />,
  "award-nominations": <Star className="h-4 w-4" />,
  communications: <Mail className="h-4 w-4" />,
  newsletters: <Mail className="h-4 w-4" />,
  "notification-system": <Bell className="h-4 w-4" />,
  "announcement-management": <Megaphone className="h-4 w-4" />,
  "calendar-integration": <CalendarCheck className="h-4 w-4" />,
  analytics: <BarChart3 className="h-4 w-4" />,
  "event-analytics": <Calendar className="h-4 w-4" />,
  "financial-analytics": <DollarSign className="h-4 w-4" />,
  "content-analytics": <FileText className="h-4 w-4" />,
  "custom-reports": <FileText className="h-4 w-4" />,
  "system-settings": <Settings className="h-4 w-4" />,
  "general-settings": <Cog className="h-4 w-4" />,
  "security-settings": <ShieldCheck className="h-4 w-4" />,
  "oauth-settings": <Key className="h-4 w-4" />,
  "payment-settings": <CreditCard className="h-4 w-4" />,
  "email-settings": <Mail className="h-4 w-4" />,
  "system-tools": <Terminal className="h-4 w-4" />,
  "database-tools": <Database className="h-4 w-4" />,
  "cache-management": <HardDrive className="h-4 w-4" />,
  "system-logs": <FileClock className="h-4 w-4" />,
  "backup-restore": <Download className="h-4 w-4" />,
  "personal-settings": <Settings className="h-4 w-4" />,
  profile: <UserCog className="h-4 w-4" />,
  preferences: <Palette className="h-4 w-4" />,
};

function withIcons(items: readonly NavItemData[]): readonly NavigationItem[] {
  return items.map((item) => ({
    ...item,
    icon: icons[item.id] ?? <FileText className="h-4 w-4" />,
    module: getModuleForPath(item.path) ?? undefined,
    subItems: item.subItems ? withIcons(item.subItems) : undefined,
  }));
}

export const navigationConfig: readonly NavigationItem[] = withIcons(navigationData);

export { navigationCategories };
