import React from "react";
import {
  Home,
  Users,
  Calendar,
  Megaphone,
  DollarSign,
  BarChart3,
  User,
  CalendarCheck,
  CreditCard,
  Shield,
  Smartphone,
  Activity,
  Settings,
  Cog,
  FileText,
  Folder,
  Tag,
  MessageSquare,
  Mail,
  Palette,
  Building,
  Briefcase,
  Target,
  Globe,
  TrendingUp,
  Award,
  BookOpen,
  Bell,
  Lock,
  Database,
  PieChart,
  Search,
  Edit,
  Archive,
  Star,
  Clock,
  MapPin,
  Video,
  QrCode,
  CheckCircle,
  RefreshCw,
  Upload,
  Download,
  ShoppingBag,
  Receipt,
  Gift,
  Printer,
  Share2,
  Eye,
  EyeOff,
  Volume2,
  Wifi,
  UserPlus,
  UserMinus,
  UserCheck,
  AlertTriangle,
  Zap,
  Layers,
  Package,
  GitBranch,
  Terminal,
  Code,
  Server,
  Cloud,
  Cpu,
  HardDrive,
  Monitor,
  Tablet,
  Headphones,
  Camera,
  Mic,
  Play,
  Pause,
  Square,
  Music,
  File,
  Trash2,
  Copy,
  Move,
  Plus,
  Minus,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  MoreVertical,
  MoreHorizontal,
  Menu,
  X,
  LogIn,
  LogOut,
  Key,
  ShieldCheck,
  UserX,
  UserLock,
  Fingerprint,
  IdCard,
  Wallet,
  Coins,
  PiggyBank,
  Building2,
  Store,
  Factory,
  Trees,
  Mountain,
  Sun,
  Moon,
  Thermometer,
  Droplets,
  Flame,
  Battery,
  Signal,
  Bluetooth,
  Usb,
  Router,
  Antenna,
  Compass,
  Map,
  Navigation,
  Navigation2,
  Anchor,
  Car,
  Truck,
  Plane,
  Ship,
  Bike,
  Tent,
  Flower,
  Sprout,
  Leaf,
  Brain,
  Heart,
  Smile,
  Laugh,
  Luggage,
  Rocket,
  TreePine,
  Trophy,
  Flag,
  Book,
  GraduationCap,
  Medal,
  Crown,
  Pin,
  Globe2,
  Users2,
  UserCircle,
  UserCog,
  UserCheck as UserCheckIcon,
  UserPlus as UserPlusIcon,
  UserX as UserXIcon,
  UserMinus as UserMinusIcon,
  BadgeCheck as BadgeCheckIcon,
  BellRing,
  MessageCircle,
  Send,
  Paperclip,
  Image as ImageIcon,
  Film,
  Music as MusicIcon,
  File as FileIcon,
  FolderOpen,
  Hash,
  Link,
  Link2,
  ExternalLink,
  Copy as CopyIcon,
  Scan,
  ScanLine,
  Save,
  Import,
  FileDown,
  FileUp,
  FileCheck,
  FileX,
  FilePlus,
  FileMinus,
  FileSearch,
  FileStack,
  FileArchive,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode,
  FileSpreadsheet,
  FileBox,
  FileHeart,
  FileVolume,
  FileDigit,
  FileClock,
} from "lucide-react";
import { UserRole } from "@/types/dashboard.types";

export interface NavigationItem {
  readonly id: string;
  readonly title: string;
  readonly icon: React.ReactNode;
  readonly path: string;
  readonly badge?: string | null;
  readonly roles?: UserRole[];
  readonly category?: "main" | "personal" | "admin" | "system";
  readonly subItems?: readonly NavigationItem[];
  readonly isActive?: boolean;
}

export const navigationConfig: readonly NavigationItem[] = [
  // Dashboard Overview
  {
    id: "dashboard",
    title: "Dashboard",
    icon: <Home className="h-4 w-4" />,
    path: "/dashboard",
    category: "main",
    roles: ["user", "member", "member_student", "member_professional", "member_corporate", "moderator", "organizer", "committee_chair", "chapter_admin", "chapter_president", "staff", "treasurer", "admin", "superadmin"],
  },

  // User Management Section
  {
    id: "user-management",
    title: "User Management",
    icon: <UserCog className="h-4 w-4" />,
    path: "/dashboard/users",
    category: "admin",
    roles: ["admin", "superadmin", "staff"],
    subItems: [
      {
        id: "user-directory",
        title: "User Directory",
        icon: <Users className="h-4 w-4" />,
        path: "/dashboard/users/directory",
        roles: ["admin", "superadmin", "staff"],
      },
      {
        id: "user-roles",
        title: "User Roles & Permissions",
        icon: <ShieldCheck className="h-4 w-4" />,
        path: "/dashboard/users/roles",
        roles: ["admin", "superadmin"],
      },
      {
        id: "user-security",
        title: "Security & Access",
        icon: <Lock className="h-4 w-4" />,
        path: "/dashboard/users/security",
        roles: ["admin", "superadmin"],
      },
    ] as const,
  },

  // Membership Management Section
  {
    id: "memberships",
    title: "Memberships",
    icon: <Users className="h-4 w-4" />,
    path: "/dashboard/memberships",
    category: "main",
    roles: ["admin", "staff", "chapter_admin", "chapter_president"],
    subItems: [
      {
        id: "member-directory",
        title: "Member Directory",
        icon: <Users className="h-4 w-4" />,
        path: "/dashboard/memberships/directory",
        roles: ["admin", "staff", "chapter_admin", "chapter_president", "member_corporate", "member_professional", "member", "moderator"],
      },
      {
        id: "membership-tiers",
        title: "Membership Tiers",
        icon: <Layers className="h-4 w-4" />,
        path: "/dashboard/memberships/tiers",
        roles: ["admin", "staff"],
      },
      {
        id: "membership-applications",
        title: "Applications",
        icon: <UserPlusIcon className="h-4 w-4" />,
        path: "/dashboard/memberships/applications",
        roles: ["admin", "staff", "chapter_admin", "chapter_president"],
        badge: "3",
      },
      {
        id: "membership-renewals",
        title: "Renewals",
        icon: <RefreshCw className="h-4 w-4" />,
        path: "/dashboard/memberships/renewals",
        roles: ["admin", "staff"],
      },
      {
        id: "member-analytics",
        title: "Member Analytics",
        icon: <BarChart3 className="h-4 w-4" />,
        path: "/dashboard/memberships/analytics",
        roles: ["admin", "staff", "chapter_admin", "chapter_president"],
      },
    ] as const,
  },

  // Event Management Section
  {
    id: "events",
    title: "Events",
    icon: <Calendar className="h-4 w-4" />,
    path: "/dashboard/events",
    category: "main",
    badge: "2",
    roles: ["admin", "staff", "organizer", "committee_chair", "chapter_admin", "chapter_president"],
    subItems: [
      {
        id: "event-calendar",
        title: "Event Calendar",
        icon: <CalendarCheck className="h-4 w-4" />,
        path: "/dashboard/events/calendar",
        roles: ["user", "member", "member_student", "member_professional", "member_corporate", "moderator", "organizer", "committee_chair", "chapter_admin", "chapter_president", "staff", "treasurer", "admin", "superadmin"],
      },
      {
        id: "create-event",
        title: "Create Event",
        icon: <Plus className="h-4 w-4" />,
        path: "/dashboard/events/create",
        roles: ["admin", "staff", "organizer", "committee_chair", "chapter_admin"],
      },
      {
        id: "event-management",
        title: "Manage Events",
        icon: <Edit className="h-4 w-4" />,
        path: "/dashboard/events/manage",
        roles: ["admin", "staff", "organizer", "committee_chair", "chapter_admin"],
      },
      {
        id: "event-registrations",
        title: "Registrations",
        icon: <Users className="h-4 w-4" />,
        path: "/dashboard/events/registrations",
        roles: ["admin", "staff", "organizer", "committee_chair"],
      },
      {
        id: "event-checkin",
        title: "QR Check-in",
        icon: <QrCode className="h-4 w-4" />,
        path: "/dashboard/events/checkin",
        roles: ["admin", "staff", "organizer", "chapter_admin"],
      },
      {
        id: "event-certificates",
        title: "Certificates",
        icon: <Award className="h-4 w-4" />,
        path: "/dashboard/events/certificates",
        roles: ["admin", "staff", "organizer"],
      },
      {
        id: "event-pricing",
        title: "Pricing & Promos",
        icon: <Tag className="h-4 w-4" />,
        path: "/dashboard/events/pricing",
        roles: ["admin", "staff", "organizer"],
      },
    ] as const,
  },

  // Financial Management Section
  {
    id: "finance",
    title: "Finance",
    icon: <DollarSign className="h-4 w-4" />,
    path: "/dashboard/finance",
    category: "main",
    roles: ["admin", "treasurer", "staff"],
    subItems: [
      {
        id: "budget-management",
        title: "Budget Management",
        icon: <PieChart className="h-4 w-4" />,
        path: "/dashboard/finance/budget",
        roles: ["admin", "treasurer", "chapter_president", "committee_chair"],
      },
      {
        id: "dues-management",
        title: "Member Dues",
        icon: <CreditCard className="h-4 w-4" />,
        path: "/dashboard/finance/dues",
        roles: ["admin", "treasurer", "staff"],
      },
      {
        id: "invoices-billing",
        title: "Invoices & Billing",
        icon: <Receipt className="h-4 w-4" />,
        path: "/dashboard/finance/invoices",
        roles: ["admin", "treasurer", "staff"],
      },
      {
        id: "donations-grants",
        title: "Donations & Grants",
        icon: <Gift className="h-4 w-4" />,
        path: "/dashboard/finance/donations",
        roles: ["admin", "treasurer", "staff"],
      },
      {
        id: "financial-reports",
        title: "Financial Reports",
        icon: <BarChart3 className="h-4 w-4" />,
        path: "/dashboard/finance/reports",
        roles: ["admin", "treasurer"],
      },
      {
        id: "payment-gateways",
        title: "Payment Gateways",
        icon: <CreditCard className="h-4 w-4" />,
        path: "/dashboard/finance/gateways",
        roles: ["admin", "treasurer"],
      },
    ] as const,
  },

  // Organization Structure Section
  {
    id: "organization",
    title: "Organization",
    icon: <Building className="h-4 w-4" />,
    path: "/dashboard/organization",
    category: "main",
    roles: ["admin", "chapter_president", "chapter_admin", "committee_chair"],
    subItems: [
      {
        id: "chapters",
        title: "Chapters",
        icon: <MapPin className="h-4 w-4" />,
        path: "/dashboard/organization/chapters",
        roles: ["admin", "chapter_president", "chapter_admin"],
      },
      {
        id: "committees",
        title: "Committees",
        icon: <Users2 className="h-4 w-4" />,
        path: "/dashboard/organization/committees",
        roles: ["admin", "chapter_president", "committee_chair"],
      },
      {
        id: "committee-workspaces",
        title: "Committee Workspaces",
        icon: <Briefcase className="h-4 w-4" />,
        path: "/dashboard/organization/committees/workspaces",
        roles: ["admin", "committee_chair", "member", "member_professional"],
      },
      {
        id: "committee-budgets",
        title: "Committee Budgets",
        icon: <DollarSign className="h-4 w-4" />,
        path: "/dashboard/organization/committees/budget",
        roles: ["admin", "treasurer", "committee_chair"],
      },
    ] as const,
  },

  // Content Management Section
  {
    id: "content",
    title: "Content Management",
    icon: <FileText className="h-4 w-4" />,
    path: "/dashboard/content",
    category: "main",
    roles: ["admin", "staff", "moderator"],
    subItems: [
      {
        id: "publications",
        title: "Publications",
        icon: <BookOpen className="h-4 w-4" />,
        path: "/dashboard/content/publications",
        roles: ["admin", "staff"],
      },
      {
        id: "articles-news",
        title: "Articles & News",
        icon: <FileText className="h-4 w-4" />,
        path: "/dashboard/content/articles",
        roles: ["admin", "staff", "moderator"],
      },
      {
        id: "announcements",
        title: "Announcements",
        icon: <Megaphone className="h-4 w-4" />,
        path: "/dashboard/content/announcements",
        roles: ["admin", "staff", "chapter_admin", "committee_chair"],
      },
      {
        id: "categories-tags",
        title: "Categories & Tags",
        icon: <Tag className="h-4 w-4" />,
        path: "/dashboard/content/categories",
        roles: ["admin", "staff"],
      },
      {
        id: "media-library",
        title: "Media Library",
        icon: <ImageIcon className="h-4 w-4" />,
        path: "/dashboard/content/media",
        roles: ["admin", "staff"],
      },
    ] as const,
  },

  // Learning & Development Section
  {
    id: "learning",
    title: "Learning & Development",
    icon: <GraduationCap className="h-4 w-4" />,
    path: "/dashboard/learning",
    category: "main",
    roles: ["user", "member", "member_student", "member_professional", "member_corporate", "moderator", "organizer", "committee_chair", "chapter_admin", "chapter_president", "staff", "treasurer", "admin", "superadmin"],
    subItems: [
      {
        id: "courses",
        title: "Courses",
        icon: <Book className="h-4 w-4" />,
        path: "/dashboard/learning/courses",
        roles: ["user", "member", "member_student", "member_professional", "member_corporate", "admin", "staff"],
      },
      {
        id: "certifications",
        title: "Certifications",
        icon: <Award className="h-4 w-4" />,
        path: "/dashboard/learning/certifications",
        roles: ["user", "member", "member_student", "member_professional", "member_corporate", "admin", "staff"],
      },
      {
        id: "course-management",
        title: "Course Management",
        icon: <Settings className="h-4 w-4" />,
        path: "/dashboard/learning/admin",
        roles: ["admin", "staff"],
      },
    ] as const,
  },

  // Forums & Discussions Section
  {
    id: "forums",
    title: "Forums & Discussions",
    icon: <MessageSquare className="h-4 w-4" />,
    path: "/dashboard/forums",
    category: "main",
    roles: ["user", "member", "member_student", "member_professional", "member_corporate", "moderator", "organizer", "committee_chair", "chapter_admin", "chapter_president", "staff", "treasurer", "admin", "superadmin"],
    subItems: [
      {
        id: "forum-categories",
        title: "Forum Categories",
        icon: <Layers className="h-4 w-4" />,
        path: "/dashboard/forums/categories",
        roles: ["admin", "staff", "moderator"],
      },
      {
        id: "forum-moderation",
        title: "Content Moderation",
        icon: <Shield className="h-4 w-4" />,
        path: "/dashboard/forums/moderation",
        roles: ["admin", "staff", "moderator"],
      },
      {
        id: "user-reports",
        title: "User Reports",
        icon: <Flag className="h-4 w-4" />,
        path: "/dashboard/forums/reports",
        roles: ["admin", "staff", "moderator"],
      },
    ] as const,
  },

  // Job Board Section
  {
    id: "job-board",
    title: "Job Board",
    icon: <Briefcase className="h-4 w-4" />,
    path: "/dashboard/jobs",
    category: "main",
    roles: ["user", "member", "member_student", "member_professional", "member_corporate", "admin", "staff"],
    subItems: [
      {
        id: "job-postings",
        title: "Job Postings",
        icon: <Briefcase className="h-4 w-4" />,
        path: "/dashboard/jobs/postings",
        roles: ["user", "member", "member_student", "member_professional", "member_corporate", "admin", "staff"],
      },
      {
        id: "job-management",
        title: "Job Management",
        icon: <Settings className="h-4 w-4" />,
        path: "/dashboard/jobs/admin",
        roles: ["admin", "staff"],
      },
    ] as const,
  },

  // Awards & Recognition Section
  {
    id: "awards",
    title: "Awards & Recognition",
    icon: <Trophy className="h-4 w-4" />,
    path: "/dashboard/awards",
    category: "main",
    roles: ["user", "member", "member_student", "member_professional", "member_corporate", "admin", "staff"],
    subItems: [
      {
        id: "award-programs",
        title: "Award Programs",
        icon: <Medal className="h-4 w-4" />,
        path: "/dashboard/awards/programs",
        roles: ["admin", "staff", "committee_chair"],
      },
      {
        id: "award-nominations",
        title: "Nominations",
        icon: <Star className="h-4 w-4" />,
        path: "/dashboard/awards/nominations",
        roles: ["user", "member", "member_student", "member_professional", "member_corporate", "admin", "staff"],
      },
    ] as const,
  },

  // Communications Section
  {
    id: "communications",
    title: "Communications",
    icon: <Mail className="h-4 w-4" />,
    path: "/dashboard/communications",
    category: "main",
    roles: ["admin", "staff", "moderator", "chapter_admin", "committee_chair"],
    subItems: [
      {
        id: "newsletters",
        title: "Newsletters",
        icon: <Mail className="h-4 w-4" />,
        path: "/dashboard/communications/newsletters",
        roles: ["admin", "staff"],
      },
      {
        id: "notification-system",
        title: "Notification System",
        icon: <Bell className="h-4 w-4" />,
        path: "/dashboard/communications/notifications",
        roles: ["admin", "staff"],
        badge: "5",
      },
      {
        id: "announcement-management",
        title: "Announcement Management",
        icon: <Megaphone className="h-4 w-4" />,
        path: "/dashboard/communications/announcements",
        roles: ["admin", "staff", "chapter_admin", "committee_chair"],
      },
      {
        id: "calendar-integration",
        title: "Calendar Integration",
        icon: <CalendarCheck className="h-4 w-4" />,
        path: "/dashboard/communications/calendar",
        roles: ["admin", "staff"],
      },
    ] as const,
  },

  // Analytics & Reports Section
  {
    id: "analytics",
    title: "Analytics & Reports",
    icon: <BarChart3 className="h-4 w-4" />,
    path: "/dashboard/analytics",
    category: "main",
    roles: ["admin", "staff", "treasurer", "chapter_admin", "chapter_president"],
    subItems: [
      {
        id: "member-analytics",
        title: "Member Analytics",
        icon: <Users className="h-4 w-4" />,
        path: "/dashboard/analytics/members",
        roles: ["admin", "staff", "chapter_admin", "chapter_president"],
      },
      {
        id: "event-analytics",
        title: "Event Analytics",
        icon: <Calendar className="h-4 w-4" />,
        path: "/dashboard/analytics/events",
        roles: ["admin", "staff", "organizer", "chapter_admin"],
      },
      {
        id: "financial-analytics",
        title: "Financial Analytics",
        icon: <DollarSign className="h-4 w-4" />,
        path: "/dashboard/analytics/financial",
        roles: ["admin", "treasurer"],
      },
      {
        id: "content-analytics",
        title: "Content Analytics",
        icon: <FileText className="h-4 w-4" />,
        path: "/dashboard/analytics/content",
        roles: ["admin", "staff", "moderator"],
      },
      {
        id: "custom-reports",
        title: "Custom Reports",
        icon: <FileText className="h-4 w-4" />,
        path: "/dashboard/analytics/custom",
        roles: ["admin", "staff", "treasurer"],
      },
    ] as const,
  },

  // System Settings & Administration
  {
    id: "system-settings",
    title: "System Settings",
    icon: <Settings className="h-4 w-4" />,
    path: "/dashboard/settings/system",
    category: "admin",
    roles: ["admin", "superadmin"],
    subItems: [
      {
        id: "general-settings",
        title: "General Settings",
        icon: <Cog className="h-4 w-4" />,
        path: "/dashboard/settings/general",
        roles: ["admin", "superadmin"],
      },
      {
        id: "security-settings",
        title: "Security Configuration",
        icon: <ShieldCheck className="h-4 w-4" />,
        path: "/dashboard/settings/security",
        roles: ["admin", "superadmin"],
      },
      {
        id: "oauth-settings",
        title: "OAuth Configuration",
        icon: <Key className="h-4 w-4" />,
        path: "/dashboard/settings/oauth",
        roles: ["admin", "superadmin"],
      },
      {
        id: "payment-settings",
        title: "Payment Gateway Settings",
        icon: <CreditCard className="h-4 w-4" />,
        path: "/dashboard/settings/payments",
        roles: ["admin", "treasurer", "superadmin"],
      },
      {
        id: "email-settings",
        title: "Email Configuration",
        icon: <Mail className="h-4 w-4" />,
        path: "/dashboard/settings/email",
        roles: ["admin", "superadmin"],
      },
    ] as const,
  },
  {
    id: "system-tools",
    title: "System Tools",
    icon: <Terminal className="h-4 w-4" />,
    path: "/dashboard/tools",
    category: "admin",
    roles: ["admin", "superadmin"],
    subItems: [
      {
        id: "database-tools",
        title: "Database Tools",
        icon: <Database className="h-4 w-4" />,
        path: "/dashboard/tools/database",
        roles: ["admin", "superadmin"],
      },
      {
        id: "cache-management",
        title: "Cache Management",
        icon: <HardDrive className="h-4 w-4" />,
        path: "/dashboard/tools/cache",
        roles: ["admin", "superadmin"],
      },
      {
        id: "system-logs",
        title: "System Logs",
        icon: <FileClock className="h-4 w-4" />,
        path: "/dashboard/tools/logs",
        roles: ["admin", "superadmin"],
      },
      {
        id: "backup-restore",
        title: "Backup & Restore",
        icon: <Download className="h-4 w-4" />,
        path: "/dashboard/tools/backup",
        roles: ["admin", "superadmin"],
      },
    ] as const,
  },
] as const;

export const navigationCategories = {
  main: "Main Navigation",
  admin: "Administration",
} as const;