import type { NavItemData } from "./types";

export const personalSettingsSection: readonly NavItemData[] = [
  // Personal Settings Section
  {
    id: "personal-settings",
    title: "Personal Settings",
    path: "/dashboard/profile",
    category: "personal",
    roles: [
      "user",
      "member",
      "member_student",
      "member_professional",
      "member_corporate",
      "moderator",
      "organizer",
      "committee_chair",
      "chapter_admin",
      "chapter_president",
      "staff",
      "treasurer",
      "admin",
      "superadmin",
    ],
    subItems: [
      {
        id: "profile",
        title: "Profile",
        path: "/dashboard/profile",
        roles: [
          "user",
          "member",
          "member_student",
          "member_professional",
          "member_corporate",
          "moderator",
          "organizer",
          "committee_chair",
          "chapter_admin",
          "chapter_president",
          "staff",
          "treasurer",
          "admin",
          "superadmin",
        ],
      },
      {
        id: "preferences",
        title: "Preferences",
        path: "/dashboard/preferences",
        roles: [
          "user",
          "member",
          "member_student",
          "member_professional",
          "member_corporate",
          "moderator",
          "organizer",
          "committee_chair",
          "chapter_admin",
          "chapter_president",
          "staff",
          "treasurer",
          "admin",
          "superadmin",
        ],
      },
    ] as const,
  },
] as const;
