import { AVAILABLE_PERMISSIONS } from "./available-permissions";
import type { Permission } from "./permission-types";

export const ADMIN_ROLE_PERMISSIONS: Record<
  "superadmin" | "admin" | "staff" | "treasurer",
  Permission[]
> = {
  superadmin: AVAILABLE_PERMISSIONS, // All permissions

  admin: [
    // Full access except system-level
    "users:create",
    "users:read",
    "users:update",
    "users:delete",
    "users:manage",
    "users:export",
    "users:import",
    "events:create",
    "events:read",
    "events:update",
    "events:delete",
    "events:manage",
    "events:publish",
    "events:approve",
    "memberships:create",
    "memberships:read",
    "memberships:update",
    "memberships:delete",
    "memberships:manage",
    "memberships:approve",
    "memberships:export",
    "finance:create",
    "finance:read",
    "finance:update",
    "finance:delete",
    "finance:manage",
    "finance:approve",
    "finance:export",
    "content:create",
    "content:read",
    "content:update",
    "content:delete",
    "content:manage",
    "content:publish",
    "content:approve",
    "communications:create",
    "communications:read",
    "communications:update",
    "communications:delete",
    "communications:manage",
    "communications:publish",
    "analytics:read",
    "analytics:export",
    "analytics:manage",
    "organization:create",
    "organization:read",
    "organization:update",
    "organization:delete",
    "organization:manage",
    "forum:create",
    "forum:read",
    "forum:update",
    "forum:delete",
    "forum:manage",
    "forum:moderate",
    "jobs:create",
    "jobs:read",
    "jobs:update",
    "jobs:delete",
    "jobs:manage",
    "jobs:approve",
    "learning:create",
    "learning:read",
    "learning:update",
    "learning:delete",
    "learning:manage",
    "learning:approve",
    "chapters:create",
    "chapters:read",
    "chapters:update",
    "chapters:delete",
    "chapters:manage",
    "committees:create",
    "committees:read",
    "committees:update",
    "committees:delete",
    "committees:manage",
    "awards:create",
    "awards:read",
    "awards:update",
    "awards:delete",
    "awards:manage",
    "workspaces:create",
    "workspaces:read",
    "workspaces:update",
    "workspaces:delete",
    "workspaces:manage",
  ],

  staff: [
    // Operational access, no user management or system settings
    "events:create",
    "events:read",
    "events:update",
    "events:manage",
    "events:publish",
    "memberships:read",
    "memberships:update",
    "memberships:manage",
    "content:create",
    "content:read",
    "content:update",
    "content:publish",
    "communications:create",
    "communications:read",
    "communications:update",
    "communications:publish",
    "analytics:read",
    "analytics:export",
    "forum:read",
    "forum:manage",
    "forum:moderate",
    "jobs:read",
    "jobs:update",
    "jobs:manage",
    "jobs:approve",
    "learning:read",
    "learning:update",
    "learning:manage",
    "chapters:read",
    "chapters:update",
    "chapters:manage",
    "committees:read",
    "committees:update",
    "committees:manage",
    "awards:read",
    "awards:update",
    "awards:manage",
    "workspaces:read",
    "workspaces:update",
    "workspaces:manage",
    "organization:read",
  ],

  treasurer: [
    // Financial focus
    "finance:create",
    "finance:read",
    "finance:update",
    "finance:manage",
    "finance:approve",
    "finance:export",
    "memberships:read",
    "memberships:update",
    "analytics:read",
    "analytics:export",
    "events:read",
    "organization:read",
  ],
};
