import { Award, Briefcase, Crown, GraduationCap, Star, User } from "lucide-react";

import { MembershipTier } from "@/types/membership.types";
import type { TierData } from "./tiers-types";

// Mock data - replace with actual API call
export const tiersData: TierData[] = [
  {
    tier: MembershipTier.BASIC,
    name: "Basic Member",
    description: "Perfect for individuals starting their professional journey",
    price: "$29",
    period: "month",
    features: [
      "Community access",
      "Basic networking",
      "Monthly newsletter",
      "Event attendance",
      "Profile directory listing",
    ],
    benefits: ["Connect with 500+ members", "Attend 2 events per month", "Access to resources"],
    memberCount: 1247,
    status: "active",
    icon: <User className="w-5 h-5" />,
    color: "blue",
    visibility: true,
    upgradeFrom: [],
    upgradeTo: ["Student Member", "Professional Member"],
    restrictions: [],
  },
  {
    tier: MembershipTier.STUDENT,
    name: "Student Member",
    description: "Special pricing for students and recent graduates",
    price: "$15",
    period: "month",
    features: [
      "All Basic features",
      "Student-only events",
      "Mentorship program",
      "Career resources",
      "Academic discounts",
    ],
    benefits: ["50% discount on events", "Free mentorship matching", "Career coaching sessions"],
    memberCount: 523,
    status: "active",
    icon: <GraduationCap className="w-5 h-5" />,
    color: "green",
    visibility: true,
    upgradeFrom: ["Basic Member"],
    upgradeTo: ["Professional Member", "VIP Member"],
    restrictions: ["Valid student ID required"],
  },
  {
    tier: MembershipTier.PROFESSIONAL,
    name: "Professional Member",
    description: "Ideal for established professionals and experts",
    price: "$79",
    period: "month",
    features: [
      "All Basic features",
      "Premium networking",
      "Advanced analytics",
      "Lead generation tools",
      "Priority support",
      "Webinar hosting",
    ],
    benefits: [
      "Unlimited event access",
      "Featured profile placement",
      "Advanced member directory",
      "Business development resources",
    ],
    memberCount: 892,
    status: "popular",
    icon: <Award className="w-5 h-5" />,
    color: "purple",
    visibility: true,
    upgradeFrom: ["Basic Member", "Student Member"],
    upgradeTo: ["VIP Member", "Premium Member"],
    restrictions: [],
  },
  {
    tier: MembershipTier.CORPORATE,
    name: "Corporate Member",
    description: "Comprehensive solution for teams and organizations",
    price: "$299",
    period: "month",
    features: [
      "All Professional features",
      "Team management",
      "Corporate branding",
      "Bulk event tickets",
      "Dedicated support",
      "Custom integrations",
    ],
    benefits: [
      "Up to 10 team members",
      "Company branding opportunities",
      "Exclusive corporate events",
      "Volume discounts",
    ],
    memberCount: 156,
    status: "active",
    icon: <Briefcase className="w-5 h-5" />,
    color: "orange",
    visibility: true,
    upgradeFrom: ["Professional Member"],
    upgradeTo: ["Premium Member"],
    restrictions: ["Minimum 5 team members"],
  },
  {
    tier: MembershipTier.VIP,
    name: "VIP Member",
    description: "Premium experience for industry leaders and influencers",
    price: "$199",
    period: "month",
    features: [
      "All Professional features",
      "VIP event access",
      "Executive networking",
      "Personal concierge",
      "Exclusive content",
      "One-on-one coaching",
    ],
    benefits: [
      "Invitation-only events",
      "Personal brand consulting",
      "Priority speaking opportunities",
      "Elite networking circles",
    ],
    memberCount: 89,
    status: "active",
    icon: <Star className="w-5 h-5" />,
    color: "yellow",
    visibility: true,
    upgradeFrom: ["Professional Member", "Student Member"],
    upgradeTo: ["Premium Member"],
    restrictions: ["Invitation only", "Industry leader status required"],
  },
  {
    tier: MembershipTier.PREMIUM,
    name: "Premium Member",
    description: "Ultimate membership experience with maximum benefits",
    price: "$399",
    period: "month",
    features: [
      "All VIP features",
      "Lifetime directory listing",
      "Content creation tools",
      "Advanced analytics",
      "API access",
      "White-label opportunities",
    ],
    benefits: [
      "Lifetime membership option",
      "Revenue sharing program",
      "Board nomination eligibility",
      "Premium advertising placement",
    ],
    memberCount: 47,
    status: "active",
    icon: <Crown className="w-5 h-5" />,
    color: "red",
    visibility: true,
    upgradeFrom: ["VIP Member", "Corporate Member"],
    upgradeTo: [],
    restrictions: ["Board approval required"],
  },
];
